const express = require('express');
const jwt = require('jsonwebtoken');
const { v4: uuidv4 } = require('uuid');
const { hashPassword, comparePassword } = require('../lib/hash');
const db = require('../lib/db');
const config = require('../lib/config');
const { loginLimiter, registrationLimiter } = require('../middleware/rateLimiter');
const { requireAuth } = require('../middleware/auth');
const {
  sendVerificationEmail,
  sendPasswordResetEmail,
  sendChildLockoutNotification,
} = require('../lib/email');

const router = express.Router();

// ─── POST /api/auth/register ──────────────────────────────
router.post('/register', registrationLimiter, async (req, res) => {
  try {
    // Check feature flags
    try {
      const [regResult, payResult] = await Promise.all([
        db.query("SELECT enabled FROM feature_flag WHERE key = 'registration_enabled' LIMIT 1"),
        db.query("SELECT enabled FROM feature_flag WHERE key = 'payment_mode' LIMIT 1"),
      ]);

      const registrationEnabled = regResult.rows.length > 0 ? regResult.rows[0].enabled : true;
      const paymentMode = payResult.rows.length > 0 ? payResult.rows[0].enabled : false;

      if (!registrationEnabled) {
        return res.status(403).json({ error: 'Registrering är för närvarande stängd' });
      }

      const inviteToken = req.body.invite || req.query.invite;
      if (paymentMode && !inviteToken) {
        return res.status(403).json({ error: 'Registrering kräver en inbjudan' });
      }
    } catch (flagErr) {
      console.error('[AUTH] Feature flag check error:', flagErr);
      // Fail open — allow registration if flag check fails
    }

    const { email, password, name, family_name } = req.body;

    if (!email || !password) {
      return res.status(400).json({ error: 'E-post och lösenord krävs' });
    }
    if (typeof email !== 'string' || !email.includes('@')) {
      return res.status(400).json({ error: 'Ogiltig e-postadress' });
    }
    if (password.length < 8) {
      return res.status(400).json({ error: 'Lösenordet måste vara minst 8 tecken' });
    }

    // Validate name — required for auto-generating family name
    if (!name || typeof name !== 'string' || name.trim().length < 1) {
      return res.status(400).json({ error: 'Namn krävs för att skapa ett familjkonto' });
    }
    const trimmedName = name.trim();
    const isFamilyNameAutoGenerated = !family_name || family_name.trim() === '';
    const finalFamilyName = isFamilyNameAutoGenerated
      ? `${trimmedName}s familj`
      : family_name.trim();

    const normalizedEmail = email.toLowerCase().trim();

    // Check if email exists
    const existing = await db.query(
      'SELECT id FROM parent WHERE LOWER(email) = $1',
      [normalizedEmail]
    );
    if (existing.rows.length > 0) {
      return res.status(409).json({ error: 'Det finns redan ett konto med den e-postadressen' });
    }

    const passwordHash = await hashPassword(password);
    const client = await db.getClient();

    try {
      await client.query('BEGIN');

      // Create family (with auto-generated or user-provided name)
      const familyResult = await client.query(
        'INSERT INTO family (name) VALUES ($1) RETURNING id',
        [finalFamilyName]
      );
      const familyId = familyResult.rows[0].id;

      // Create parent (auto-verified — email delivery via proxy is currently broken)
      const parentResult = await client.query(
        'INSERT INTO parent (family_id, email, password_hash, name, verified) VALUES ($1, $2, $3, $4, true) RETURNING id',
        [familyId, normalizedEmail, passwordHash, trimmedName]
      );
      const parentId = parentResult.rows[0].id;

      // Load admin-defined default templates (falls back to hardcoded if table doesn't exist yet)
      let defaultActivities;
      try {
        const tplResult = await client.query(
          'SELECT name, icon, category_name, star_value, sort_order FROM default_activity_template ORDER BY category_name, sort_order ASC'
        );
        defaultActivities = tplResult.rows.length > 0
          ? tplResult.rows.map(r => ({ name: r.name, icon: r.icon, category: r.category_name, star_value: r.star_value }))
          : null;
      } catch {
        defaultActivities = null; // table doesn't exist yet
      }

      if (!defaultActivities) {
        defaultActivities = [
          { name: 'Vakna',                   icon: '🛏️', category: 'Morgon',      star_value: 1 },
          { name: 'Klä på sig',              icon: '🌟', category: 'Morgon',      star_value: 1 },
          { name: 'Borsta tänderna',          icon: '🪥', category: 'Morgon',      star_value: 1 },
          { name: 'Äta frukost',             icon: '🍳', category: 'Morgon',      star_value: 1 },
          { name: 'Förskola/Skola',          icon: '🏫', category: 'Förmiddag',   star_value: 1 },
          { name: 'Leka ute',                icon: '🛝', category: 'Förmiddag',   star_value: 1 },
          { name: 'Pyssel',                  icon: '🎨', category: 'Förmiddag',   star_value: 1 },
          { name: 'Mellanmål',               icon: '🍎', category: 'Eftermiddag', star_value: 1 },
          { name: 'Leka',                    icon: '🧩', category: 'Eftermiddag', star_value: 1 },
          { name: 'Träning/Aktivitet',       icon: '🏃', category: 'Eftermiddag', star_value: 1 },
          { name: 'Middag',                  icon: '🍽️', category: 'Kväll',       star_value: 1 },
          { name: 'Borsta tänderna (kväll)',  icon: '🪥', category: 'Kväll',       star_value: 1 },
          { name: 'Pyjamas',                 icon: '🧸', category: 'Kväll',       star_value: 1 },
          { name: 'Godnattsaga',             icon: '📕', category: 'Kväll',       star_value: 1 },
          { name: 'Sova',                    icon: '😴', category: 'Kväll',       star_value: 1 },
        ];
      }

      // Create categories from the unique category names in defaults
      const categoryNames = [...new Set(defaultActivities.map(a => a.category))];
      const defaultCategorySort = { 'Morgon': 10, 'Förmiddag': 20, 'Eftermiddag': 30, 'Kväll': 40 };
      const categoryMap = {};
      for (const catName of categoryNames) {
        const sortOrder = defaultCategorySort[catName] || 50;
        const catResult = await client.query(
          'INSERT INTO category (family_id, name, sort_order, is_default) VALUES ($1, $2, $3, true) RETURNING id',
          [familyId, catName, sortOrder]
        );
        categoryMap[catName] = catResult.rows[0].id;
      }

      // Seed activity templates
      for (const act of defaultActivities) {
        await client.query(
          'INSERT INTO activity_template (family_id, name, icon, category_id, star_value, is_favorite) VALUES ($1, $2, $3, $4, $5, false)',
          [familyId, act.name, act.icon, categoryMap[act.category], act.star_value]
        );
      }

      // Create notification preferences
      await client.query(
        'INSERT INTO notification_preference (parent_id) VALUES ($1)',
        [parentId]
      );

      await client.query('COMMIT');

      // Create verification token
      const verifyToken = uuidv4();
      await db.query(
        'INSERT INTO email_verification (parent_id, token, expires_at) VALUES ($1, $2, $3)',
        [parentId, verifyToken, new Date(Date.now() + config.verification.tokenExpiryHours * 3600_000)]
      );

      await sendVerificationEmail(normalizedEmail, verifyToken);

      res.status(201).json({
        message: 'Konto skapat! Kontrollera din e-post för att verifiera ditt konto.',
        parentId,
        family_name: finalFamilyName,
        is_family_name_auto_generated: isFamilyNameAutoGenerated,
        parent_name: trimmedName,
        ...(process.env.NODE_ENV !== 'production' && { verifyToken }),
      });
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }
  } catch (err) {
    console.error('[AUTH] Register error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/login ─────────────────────────────────
router.post('/login', loginLimiter, async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({ error: 'E-post och lösenord krävs' });
    }

    const normalizedEmail = email.toLowerCase().trim();
    const result = await db.query(
      'SELECT id, family_id, email, password_hash, verified, is_admin, COALESCE(locked, false) as locked FROM parent WHERE LOWER(email) = $1',
      [normalizedEmail]
    );

    // Log attempt
    await db.query(
      'INSERT INTO login_attempt (identifier, ip_address, success) VALUES ($1, $2, $3)',
      [normalizedEmail, req.ip || 'unknown', false]
    );

    const parent = result.rows[0];
    if (!parent || !(await comparePassword(password, parent.password_hash))) {
      return res.status(401).json({ error: 'Felaktig e-post eller lösenord' });
    }

    if (parent.locked) {
      return res.status(403).json({ error: 'Ditt konto har spärrats. Kontakta administratören.' });
    }

    if (!parent.verified) {
      return res.status(403).json({ error: 'Du behöver verifiera din e-postadress först' });
    }

    // Mark attempt as success
    await db.query(
      `UPDATE login_attempt SET success = true
       WHERE identifier = $1 AND created_at >= NOW() - INTERVAL '1 second'`,
      [normalizedEmail]
    );

    const token = jwt.sign(
      {
        id: parent.id,
        type: 'parent',
        familyId: parent.family_id,
        email: parent.email,
        isAdmin: parent.is_admin,
      },
      config.jwt.secret,
      { expiresIn: config.jwt.expiresIn }
    );

    res.json({
      token,
      user: {
        id: parent.id,
        email: parent.email,
        familyId: parent.family_id,
        isAdmin: parent.is_admin,
        type: 'parent',
      },
    });
  } catch (err) {
    console.error('[AUTH] Login error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/verify-email ──────────────────────────
router.post('/verify-email', async (req, res) => {
  try {
    const { token } = req.body;
    if (!token) {
      return res.status(400).json({ error: 'Verifieringstoken krävs' });
    }

    const result = await db.query(
      'SELECT id, parent_id, expires_at FROM email_verification WHERE token = $1',
      [token]
    );

    const verification = result.rows[0];
    if (!verification || new Date(verification.expires_at) < new Date()) {
      return res.status(400).json({ error: 'Ogiltig eller utgången verifieringslänk' });
    }

    await db.query('UPDATE parent SET verified = true WHERE id = $1', [verification.parent_id]);
    await db.query('DELETE FROM email_verification WHERE id = $1', [verification.id]);

    res.json({ message: 'E-postadressen har verifierats! Du kan nu logga in.' });
  } catch (err) {
    console.error('[AUTH] Verify error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/forgot-password ───────────────────────
router.post('/forgot-password', loginLimiter, async (req, res) => {
  try {
    const { email } = req.body;
    if (!email) {
      return res.status(400).json({ error: 'E-postadress krävs' });
    }

    const normalizedEmail = email.toLowerCase().trim();
    const successMessage = 'Om e-postadressen finns i vårt system har vi skickat en återställningslänk.';

    const result = await db.query(
      'SELECT id FROM parent WHERE LOWER(email) = $1',
      [normalizedEmail]
    );

    if (result.rows.length === 0) {
      return res.json({ message: successMessage });
    }

    const parentId = result.rows[0].id;

    // Invalidate existing tokens
    await db.query(
      'UPDATE password_reset SET used = true WHERE parent_id = $1 AND used = false',
      [parentId]
    );

    // Create new token
    const resetToken = uuidv4();
    await db.query(
      'INSERT INTO password_reset (parent_id, token, expires_at) VALUES ($1, $2, $3)',
      [parentId, resetToken, new Date(Date.now() + config.verification.resetTokenExpiryHours * 3600_000)]
    );

    const emailResult = await sendPasswordResetEmail(normalizedEmail, resetToken);
    if (!emailResult || !emailResult.success) {
      console.error('[AUTH] Password reset email delivery failed:', emailResult);
    } else {
      console.log('[AUTH] Password reset email sent to:', normalizedEmail, 'via', emailResult.provider);
    }

    res.json({
      message: successMessage,
      ...(process.env.NODE_ENV !== 'production' && { resetToken }),
    });
  } catch (err) {
    console.error('[AUTH] Forgot password error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/reset-password ────────────────────────
router.post('/reset-password', async (req, res) => {
  try {
    const { token, password } = req.body;
    if (!token || !password) {
      return res.status(400).json({ error: 'Token och lösenord krävs' });
    }
    if (password.length < 8) {
      return res.status(400).json({ error: 'Lösenordet måste vara minst 8 tecken' });
    }

    const result = await db.query(
      'SELECT id, parent_id, expires_at, used FROM password_reset WHERE token = $1',
      [token]
    );

    const reset = result.rows[0];
    if (!reset || reset.used || new Date(reset.expires_at) < new Date()) {
      return res.status(400).json({ error: 'Ogiltig eller utgången återställningslänk' });
    }

    const passwordHash = await hashPassword(password);
    const client = await db.getClient();

    try {
      await client.query('BEGIN');
      await client.query('UPDATE parent SET password_hash = $1 WHERE id = $2', [passwordHash, reset.parent_id]);
      await client.query('UPDATE password_reset SET used = true WHERE id = $1', [reset.id]);
      await client.query('COMMIT');
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }

    res.json({ message: 'Lösenordet har ändrats! Du kan nu logga in.' });
  } catch (err) {
    console.error('[AUTH] Reset password error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── POST /api/auth/child-login ───────────────────────────
router.post('/child-login', loginLimiter, async (req, res) => {
  try {
    const { username, pin } = req.body;
    if (!username || !pin) {
      return res.status(400).json({ error: 'Namn och PIN-kod krävs' });
    }
    if (!/^\d{4}$/.test(pin)) {
      return res.status(400).json({ error: 'PIN-koden måste vara 4 siffror' });
    }

    const normalizedInput = username.toLowerCase().trim();

    // Check recent failures for lockout BEFORE attempting login
    const lockoutWindowMs = config.rateLimits.childLogin?.windowMs || 5 * 60_000; // 5 min default
    const lockoutMax = config.rateLimits.childLogin?.max || 5; // 5 attempts default
    const lockoutSeconds = Math.floor(lockoutWindowMs / 1000);
    const failureResult = await db.query(
      `SELECT COUNT(*) as count FROM login_attempt
       WHERE identifier = $1 AND success = false
       AND created_at >= NOW() - INTERVAL '1 second' * $2`,
      [normalizedInput, lockoutSeconds]
    );

    if (parseInt(failureResult.rows[0].count) >= lockoutMax) {
      // Notify parent (try both name and username lookup)
      const parentResult = await db.query(
        `SELECT p.email, c.name FROM child c
         JOIN parent_child pc ON pc.child_id = c.id
         JOIN parent p ON p.id = pc.parent_id
         WHERE LOWER(c.username) = $1 OR LOWER(c.name) = $1 LIMIT 1`,
        [normalizedInput]
      );
      if (parentResult.rows[0]) {
        await sendChildLockoutNotification(parentResult.rows[0].email, parentResult.rows[0].name);
      }

      return res.status(429).json({
        error: `För många felaktiga försök. Kontot är låst i ${Math.floor(lockoutWindowMs / 60_000)} minuter.`,
        locked: true,
      });
    }

    // Find child — first try exact username match, then try by display name
    let childResult = await db.query(
      'SELECT id, family_id, name, emoji, username, pin FROM child WHERE LOWER(username) = $1',
      [normalizedInput]
    );

    let child = childResult.rows[0];

    // If no username match, try by display name (case-insensitive)
    if (!child) {
      const nameResult = await db.query(
        'SELECT id, family_id, name, emoji, username, pin FROM child WHERE LOWER(name) = $1',
        [normalizedInput]
      );
      if (nameResult.rows.length === 1) {
        child = nameResult.rows[0];
      } else if (nameResult.rows.length > 1) {
        for (const candidate of nameResult.rows) {
          if (await comparePassword(pin, candidate.pin)) {
            child = candidate;
            break;
          }
        }
        if (!child) {
          // Log failed attempt ONLY after actual PIN verification failure
          await db.query(
            'INSERT INTO login_attempt (identifier, ip_address, success) VALUES ($1, $2, false)',
            [normalizedInput, req.ip || 'unknown']
          );
          return res.status(401).json({ error: 'Felaktigt namn eller PIN-kod' });
        }
      }
    }

    if (!child || !(await comparePassword(pin, child.pin))) {
      // Log failed attempt ONLY after actual PIN verification failure
      await db.query(
        'INSERT INTO login_attempt (identifier, ip_address, success) VALUES ($1, $2, false)',
        [normalizedInput, req.ip || 'unknown']
      );
      return res.status(401).json({ error: 'Felaktigt namn eller PIN-kod' });
    }

    // Log successful attempt
    await db.query(
      'INSERT INTO login_attempt (identifier, ip_address, success) VALUES ($1, $2, true)',
      [normalizedInput, req.ip || 'unknown']
    );

    const token = jwt.sign(
      {
        id: child.id,
        type: 'child',
        familyId: child.family_id,
        username: child.username,
        name: child.name,
      },
      config.jwt.secret,
      { expiresIn: config.jwt.childExpiresIn }
    );

    res.json({
      token,
      user: {
        id: child.id,
        name: child.name,
        emoji: child.emoji,
        familyId: child.family_id,
        username: child.username,
        type: 'child',
      },
    });
  } catch (err) {
    console.error('[AUTH] Child login error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

// ─── GET /api/auth/me ─────────────────────────────────────
router.get('/me', requireAuth, async (req, res) => {
  try {
    if (req.user.type === 'parent') {
      const parentResult = await db.query(
        `SELECT id, email, family_id, is_admin, verified, created_at
         FROM parent WHERE id = $1`,
        [req.user.id]
      );
      if (parentResult.rows.length === 0) {
        return res.status(404).json({ error: 'Användare hittades inte' });
      }

      const parent = parentResult.rows[0];
      const childrenResult = await db.query(
        `SELECT c.id, c.name, c.emoji, c.username
         FROM child c
         JOIN parent_child pc ON pc.child_id = c.id
         WHERE pc.parent_id = $1`,
        [req.user.id]
      );

      return res.json({
        ...parent,
        type: 'parent',
        children: childrenResult.rows,
      });
    }

    if (req.user.type === 'child') {
      const childResult = await db.query(
        `SELECT id, name, emoji, family_id, username, view_mode, timezone, birthday, created_at
         FROM child WHERE id = $1`,
        [req.user.id]
      );
      if (childResult.rows.length === 0) {
        return res.status(404).json({ error: 'Användare hittades inte' });
      }

      return res.json({ ...childResult.rows[0], type: 'child' });
    }

    res.status(400).json({ error: 'Okänd användartyp' });
  } catch (err) {
    console.error('[AUTH] Me error:', err);
    res.status(500).json({ error: 'Något gick fel. Försök igen senare.' });
  }
});

module.exports = router;
